### ISSUE TITLE
Уточнение требований по реализации Межбанковского перевода - УВЕДОМЛЕНИЕ КЛИЕНТА БАНКОМ 

### ISSUE THREAD

**Issue by paulonev** [paulonev/softwareTesting#1]
-  Необходимо уточнить способы уведомления клиента о выполнении Банком его поручений (SMS-уведомление, письмо по e-mail, звонок на номер мобильного телефона и др.)

**Comment by vliplianina** [comment]
Замечания:
1) В заголовке запроса на уточнение требований должна быть суть обращения.
На вашем примере:
"Межбанковский перевод - Уведомление клиента банком -  Уточнить требование ... <суть запроса>"
2) Описание также не содержит суть запроса. Способы уведомления приведены. Нужно точнее сформулировать, какой информации не хватает.

Нужно оформить текущие и последующие запросы с учётом замечаний. Пока ничего не ставлю.
