### ISSUE TITLE
Межбанковский перевод - Уведомление клиента Банком - Уточнить способы уведомления клиента о выполнении Банком его поручений 

### ISSUE THREAD

**Issue by paulonev** [paulonev/softwareTesting#3]
Необходимо уточнить каким образом клиенты могут быть уведомлены Банком. Варианты:
- после выполнения Банком поручения клиента, на телефон клиента приходит SMS-оповещение

- после выполнения Банком поручения клиента, на телефон клиента приходит push-уведомление из сервиса Межбанковский перевод

- после выполнения Банком поручения клиента, Банк уведомляет клиента о совершенной операции по e-mail с указанием деталей операции и статусом(выполнено, отказано...)

**Comment by vliplianina** [comment]
Принято
